### ISSUE TITLE
Provide a way to limit which components get saved on marked entities

### ISSUE THREAD

**Issue by cjhowe-us** [Zeenobit/bevy_atomic_save#1]
Just some brainstorming on a potential API:

```rs
use bevy::prelude::*;
use bevy_atomic_save::{AllowlistedComponent, AllowlistedSave};

#[derive(Component, AllowlistedComponent)]
struct MyAllowlistedComponent {
    #[not_saved]
    not_saved_but_serialized: u32,
    /* ... Serializable Player Data ... */
}

#[derive(Bundle)]
struct AllowlistedBundle {
    my_component: MyAllowlistedComponent,
    save: AllowlistedSave,
}
```

Serializing but not saving data might be useful for data that needs synchronizing across the network (and therefore needs to be serialized to be sent across the network), but isn't part of the local player's save, for example,.

**Comment by Zeenobit** [comment]
The save system doesn't really operate on individual component fields. It relies on Bevy reflection to serialize the components, so in my mind, controlling whether or not individual fields of a component are saved is outside the scope of this library.

A better approach may be to separate the network data from save data into different components.

In that scenario, I could see use cases for wanting to have some components _within a bundle_ to be serializable, but not saved. Without using procedural macros (I would like to avoid them if they're only gonna be used to cover this case), this could be implemented as a black list filter on the app level (i.e. `app.skip_save::<Foo>()`). Let me know if this would solve your case.

Alternatively, with procedural macros, we could just have bundles use `#[derive(Save)]` and introduce `#[save(ignore)]` to solve this specific issue, but that would be a completely different API than what we have now. This isn't to say it's a bad idea necessarily, just that I'd need to re-consider the entire API.

**Comment by cjhowe-us** [comment]
An allowlist or denylist could work - I'm specifically interested in an allowlist. Certainly doesn't need to be a derive macro

**Comment by Zeenobit** [comment]
What specifically would `AllowlistedSave` do, and how would it be different from `Save` as-is?

**Comment by Zeenobit** [comment]
@cjhowedev I have released a complete re-write of this library as a new crate:
https://crates.io/crates/moonshine-save

The API for customizing the save pipeline is still a bit rough and undocumented, with the new version, it's possible to filter entities based on any `ReadOnlyWorldQuery` and even customize where the saved data output goes to (for example, for networking, you probably don't wanna write to disk).

I believe this solves the problem you were trying to solve with `AllowlistedSave` and `AllowlistedComponent`.
